# 服务启动端口
server:
  port: 8088
  servlet:
    context-path: /

# jdbc配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/rabbit?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# mapper映射文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml