# server start port
server:
  port: 8088

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/rabbit?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver